from setuptools import setup, find_packages

setup(
    name="helpinghands",
    version="0.1.1",
    packages=find_packages(),
    author="Emil Rühmland",
    # author_email="emilrueh@googlemail.com",
    description="Utility functions for personal projects including data manipulation, setting up settings and logging, and OpenAI API functions.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    # url="https://github.com/emilrueh/projutils",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.6",
    install_requires=[
        "aiohttp==3.8.5",
        "aiosignal==1.3.1",
        "async-timeout==4.0.2",
        "attrs==23.1.0",
        "beautifulsoup4==4.12.2",
        "bs4==0.0.1",
        "certifi==2023.5.7",
        "cffi==1.15.1",
        "charset-normalizer==3.2.0",
        "colorama==0.4.6",
        "exceptiongroup==1.1.2",
        "frozenlist==1.4.0",
        "h11==0.14.0",
        "idna==3.4",
        "keyboard==0.13.5",
        "langdetect==1.0.9",
        "lxml==4.9.3",
        "multidict==6.0.4",
        "nordvpn-switcher==0.3.0",
        "numpy==1.25.1",
        "openai==0.27.8",
        "outcome==1.2.0",
        "pandas==2.0.3",
        "pathlib==1.0.1",
        "psutil==5.9.5",
        "pycparser==2.21",
        "pydub==0.25.1",
        "PySocks==1.7.1",
        "python-dateutil==2.8.2",
        "python-dotenv==1.0.0",
        "pytz==2023.3",
        "random-user-agent==1.0.1",
        "requests==2.31.0",
        "selenium==4.10.0",
        "six==1.16.0",
        "sniffio==1.3.0",
        "sortedcontainers==2.4.0",
        "sounddevice==0.4.6",
        "soundfile==0.12.1",
        "soupsieve==2.4.1",
        "termcolor==2.3.0",
        "tqdm==4.65.0",
        "trio==0.22.2",
        "trio-websocket==0.10.3",
        "tzdata==2023.3",
        "urllib3==2.0.4",
        "wsproto==1.2.0",
        "yarl==1.9.2",
    ],
)
